name: paymesdk
description: Flutter plugin for PayME SDK.
version: 0.0.1
homepage: https://github.com/tamdesktop/PayME-SDK-Flutter
repository: https://github.com/tamdesktop/PayME-SDK-Flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tamdesktop.paymesdkflutter.paymesdk
        pluginClass: PaymesdkPlugin
      ios:
        pluginClass: PaymesdkPlugin

